source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "7.0"

target '漫天都是小星星的说' do


pod 'AVOSCloud'

end
post_install do |installer|
installer.pods_project.targets.each do |target|
target.build_configurations.each do |config|
config.build_settings['ARCHS'] = "arm64 armv7"
end
end
end
